@startuml
header edit by yuji katsuta 2023.04.25
state 点灯

点灯 -[#blue]-> 消灯 : 消灯
消灯 -[#red]-> 点灯 : 点灯
点滅.消灯 -[#red,dashed]-> 点滅.点灯
点滅.点灯 -[#blue,dashed]-> 点滅.消灯
点灯 -r-> 点滅.点灯 : 点滅モード
点滅.点灯 -l-> 点灯 : 点灯モード
点滅.消灯 --> 点灯 : 点灯モード
点滅.点灯 -[#blue]-> 消灯.点滅モード : 消灯
消灯.点滅モード -[#red]-> 点滅.点灯 : 点灯
消灯 --> 消灯.点滅モード : 点滅モード
消灯.点滅モード --> 消灯 : 点灯モード
点滅.消灯 -[#blue]-> 消灯.点滅モード : 消灯
@enduml
